### ISSUE TITLE
RStudio addin

### ISSUE THREAD

**Issue by sbalci** [EllaKaye/distilltools#10]
Hi,
Do you plan to add RStudio addin to add posts like in blogdown https://github.com/rstudio/blogdown/blob/master/R/addin.R

**Comment by EllaKaye** [comment]
Thanks for your suggestion! That's not something I had thought about, but assuming that the code from blogdown is easily adaptable, it should be something I could figure out. Or would you be interested in looking into this and submitting a pull request?

**Comment by EllaKaye** [comment]
Ooh, just found this: [https://rstudio.github.io/rstudioaddins/](https://rstudio.github.io/rstudioaddins/). I'm excited that I'm learning new things!

So yes, it looks pretty straightforward and I'm happy to give it a go, or to accept a PR from you.

**Comment by sbalci** [comment]
I will give it a try :)

**Comment by EllaKaye** [comment]
It looks like this is another piece of the blogdown puzzle: <https://github.com/rstudio/blogdown/blob/master/inst/rstudio/addins.dcf>

See also <https://rstudio.github.io/rstudioaddins/#registering-addins>

Thanks and good luck! Let me know if you get stuck and we can try and figure it out together.

**Comment by sbalci** [comment]
Hi,
There is no need to separately register to RStudio. The addin appears when user installs the package.
See this:
https://github.com/EllaKaye/distilltools/pull/11

**Comment by mccarthy-m-g** [comment]
Oops, didn’t see this issue before submitting my pull request (since it was closed). Pull request #12 adds an RStudio addin for creating a post from template (it’s a wrapper for `distilltools::create_post_from_template()`), including a default template similar to the one made by `distill::create_post()`. This should address some of your comments in pull request #11, @sbalci.
